#!/bin/sh
##############################################################################
# Gradle start up script for POSIX generated by Gradle
##############################################################################
exec java -version >/dev/null 2>&1 || { echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH." >&2; exit 1; }
exec gradle "$@"
